version: '3'
services:
  web:
    build: .
    command: ["bundle", "exec", "rackup", "--host", "0.0.0.0", "-p", "3000", "config.ru"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
  test:
    command: bundle exec rspec
